import pandas as pd
d=pd.read_csv("salary.csv")
x=d.drop(d[["salary_gt_100k"]],axis="columns")
y=d[["salary_gt_100k"]]
from sklearn.preprocessing import LabelEncoder
l_c=LabelEncoder()
l_j=LabelEncoder()
l_d=LabelEncoder()
l_e=LabelEncoder()
x["company_n"]=l_c.fit_transform(x["company"])
x["job_n"]=l_j.fit_transform(x["job"])
x["degree_n"]=l_d.fit_transform(x["degree"])
x["experience_n"]=l_e.fit_transform(x["experience"])
print(x.head())
x_n=x.drop(x[["company","job","degree","experience"]],axis="columns")
print(x_n)
print(y)
from sklearn import tree
md=tree.DecisionTreeClassifier()
md.fit(x_n,y)
print(md.score(x_n,y))
print("Prediction 1: ",md.predict(pd.DataFrame({"company_n":[2],"job_n":[1],"degree_n":[0],"experience_n":[1]})))
print("Prediction 2: ",md.predict(pd.DataFrame({"company_n":[4],"job_n":[1],"degree_n":[0],"experience_n":[0]})))
print("Prediction 3: ",md.predict(pd.DataFrame({"company_n":[0],"job_n":[0],"degree_n":[0],"experience_n":[0]})))
print("Prediction 4: ",md.predict(pd.DataFrame({"company_n":[4],"job_n":[2],"degree_n":[0],"experience_n":[1]})))
print("Prediction 5: ",md.predict(pd.DataFrame({"company_n":[0],"job_n":[1],"degree_n":[2],"experience_n":[0]})))
print("Prediction 6: ",md.predict(pd.DataFrame({"company_n":[2],"job_n":[2],"degree_n":[1],"experience_n":[1]})))
print("Prediction 7: ",md.predict(pd.DataFrame({"company_n":[3],"job_n":[2],"degree_n":[2],"experience_n":[0]})))