import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
d=pd.read_csv("House_price_multiple_linear_Regression.csv")
x=d.drop("Price",axis=1)
y=d.Price
md=LinearRegression()
md.fit(x,y)
print("Slope: \n", md.coef_)
print("Intercept: \n", md.intercept_)
print("Prediction 1: ",md.predict(pd.DataFrame({"Area_sqft":[3040],"Bedrooms":[3],"Bathrooms":[2]})))
print("Prediction 2: ",md.predict(pd.DataFrame({"Area_sqft":[300],"Bedrooms":[1],"Bathrooms":[1]})))
print("Prediction 3: ",md.predict(pd.DataFrame({"Area_sqft":[5400],"Bedrooms":[5],"Bathrooms":[3]})))
plt.scatter(d['Area_sqft'], d['Price'])
plt.xlabel("Area (sqft)")
plt.ylabel("Price")
plt.title("Area vs Price")
plt.ticklabel_format(style='plain', axis='y')
plt.show()
plt.scatter(d['Bedrooms'], d['Price'])
plt.xlabel("Bedrooms")
plt.ylabel("Price")
plt.title("Bedrooms vs Price")
plt.ticklabel_format(style='plain', axis='y')
plt.show()
plt.scatter(d['Bathrooms'], d['Price'])
plt.xlabel("Bathrooms")
plt.ylabel("Price")
plt.title("Bathrooms vs Price")
plt.ticklabel_format(style='plain', axis='y')
plt.show()
y_pred = md.predict(x)
plt.scatter(y, y_pred)
plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.title("Actual vs Predicted Price")
plt.ticklabel_format(style='plain', axis='both')
plt.show()